import Head from 'next/head';
import {AppBar, Toolbar} from '@mui/material';
import {AccommondationList} from '@/components';
import {useHotelsSearch} from '@/hooks';
import _ from 'lodash';

export const HomePage = () => {
    const fromDate = '03/04/2024';
    const toDate = '03/11/2023';
    const groupSize = 4;
    const hotels = useHotelsSearch(1, fromDate, toDate, groupSize);

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <AppBar position={'static'}>
                <Toolbar></Toolbar>
            </AppBar>

            {
                hotels && _.isArray(hotels) &&
                <AccommondationList accommondations={hotels} fromDate={fromDate} toDate={toDate} groupSize={groupSize}/>
            }
        </>
    );
};

export default HomePage;
